### ISSUE TITLE
Criar opção para geração automática no travis

### ISSUE THREAD

**Issue by edusantana** [abntex/trabalho-academico-limarka#21]
Ajuda sobre como o processo funciona:
- https://docs.travis-ci.com/user/deployment/releases
- https://github.com/settings/tokens/new (aonde criar token de acesso)
- [encrypting-environment-variables](https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables)
Para facilitar, o mais simples é iniciar fazendo um fock de https://github.com/abntex/trabalho-academico-limarka.

As seguintes variáveis precisam ser configuradas no travis para a geração funcionar:

```yaml
EMAIL: O seu e-mail
NOME: O seu nome completo
TOKEN: O token gerado pelo link acima e com permissão 'repo' selecionada
PDF: O nome do arquivo PDF que será publicado
```

![variaveis-no-travis](https://user-images.githubusercontent.com/3603111/51480454-dabe7100-1d6f-11e9-9bb7-1aef453c0053.png)

**NOTA**: Se o usuário solicitou acesso estudantil ao github, com repositório privado, então na geração da chave deve-se dar permissão de acesso aos repositórios privados também. 

O usuário pode forçar um build manual:

![acionando-build-manual](https://user-images.githubusercontent.com/3603111/51480840-cb8bf300-1d70-11e9-8f5d-a72f55570be9.png)

Em seguida, o PDF será publicado na seção de releases do seu repositório:

![pdf-release-em-draf](https://user-images.githubusercontent.com/3603111/51481074-9338e480-1d71-11e9-8fc8-0e004cc4ac59.png)

Pronto, cada novo commit no github irá iniciar a geração do PDF.

Falta mostrar:

- atualizar o documento através do editor no github

OBS: para modificar as configurações da geração (configuracao.pdf) será necessário mais esforço, notadamente o uso do git para baixar e submeter alterações.

![forking](https://user-images.githubusercontent.com/3603111/51504741-54cb1600-1dc1-11e9-881e-bd1d96bafccf.png)

![token-tcc](https://user-images.githubusercontent.com/3603111/51504921-63fe9380-1dc2-11e9-9e5a-15eff2a82ae5.png)

Copiando token gerado:

![show-token](https://user-images.githubusercontent.com/3603111/51505006-eedf8e00-1dc2-11e9-9ab7-74520eb69033.png)

Ativando build o repositório:

![ativando-repo](https://user-images.githubusercontent.com/3603111/51505302-8db8ba00-1dc4-11e9-8cee-8469a01d2873.png)

Configure as variáveis de ambiente:

![env](https://user-images.githubusercontent.com/3603111/51505655-a6c26a80-1dc6-11e9-8e3c-98afcf4428ed.png)

Inicie o build:

![iniciando-build](https://user-images.githubusercontent.com/3603111/51505797-7f1fd200-1dc7-11e9-9a80-6e7d6f3ec9db.png)

![iniciar](https://user-images.githubusercontent.com/3603111/51505873-edfd2b00-1dc7-11e9-91ff-a9798aac7a9b.png)

Aguarde o build

![aguarde](https://user-images.githubusercontent.com/3603111/51505918-2bfa4f00-1dc8-11e9-92f5-a71187da9d86.png)

Clique no ícone do Github para voltar ao seu repositório

![volte-ao-repositorio](https://user-images.githubusercontent.com/3603111/51506013-be025780-1dc8-11e9-9732-65f26c9ea14a.png)

Clique em **releases**:

![clique-releases](https://user-images.githubusercontent.com/3603111/51506063-23564880-1dc9-11e9-86ce-43e0698f4625.png)

O seu PDF foi gerado, clique no link para acessá-lo.

![draft](https://user-images.githubusercontent.com/3603111/51506138-77f9c380-1dc9-11e9-9d3a-40f17b3f3d8e.png)

### Editar o texto

Vá para a página inicial do repositório, clique `trabalho-academico.md` e depois no lápis para editar o arquivo.

![clique-em-trabalho-academico](https://user-images.githubusercontent.com/3603111/51506324-a0ce8880-1dca-11e9-8dba-ffffac959a8d.png)

Atualize o texto inserindo qualquer coisa, depois clique em **Commit changes**.

![editando](https://user-images.githubusercontent.com/3603111/51506702-6534be00-1dcc-11e9-985f-5bd0e645c89b.png)

### Verifique nova geração

Volte ao travis, clique em **builds** e perceba que um novo build foi iniciado para geração do PDF.

![build-history](https://user-images.githubusercontent.com/3603111/51506548-93fe6480-1dcb-11e9-9041-46aad3738fd9.png)

Aguarde a geração do PDF finalizar e depois volte aos releases do repositório. Perceba que um outro PDF foi publicado:

![2-draft](https://user-images.githubusercontent.com/3603111/51506626-f6effb80-1dcb-11e9-9cda-251f9487f7a5.png)

### Verifique as alterações

Abra o PDF e verifique as alterações.

![pdf](https://user-images.githubusercontent.com/3603111/51506814-e8561400-1dcc-11e9-96f0-2f6e2e06ff7b.png)

**Comment by edusantana** [comment]
https://github.com/abntex/limarka/wiki/Gerando-releases

```yaml
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Eduardo de Santana Medeiros Alexandre"
  - git config --local user.email "eduardo.ufpb@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: Am7/vCmFFkvSL7BMC31JwaobYswii+vEnIYNLx/M0PTOrRWQNRYoh7d+dA6jNSlgs/Uv5bBptEsUclEpOkKTp8/HQcCjqqTJ7CJTyDORH23YILLNa43OdAk/qVfwV6tlAv6Y28hb/fieFjuCT6iSdcm9aD6wwx2ZvTpTE9CJt3j8lduSibAQ5q6gPLVG7RAs0wWnNJ8vbKazZi8j/+aCH/t+kQcWdrxhVj8dkva4L5Rh4FF0i1l6d5LimEdbIGXeTms8ZCnHJyalG4kQhdxuTmWyv9tzUFyRag2KtmcT5xiWnJBq4jF7lQSICJlpLCiHgJBNcILXAJmtTb4B0vilCm1Rl4Hfl5op7RgH7vuRtGOD+vduX926rVB1BC0225sWri7kCYL82JiupnP9LQnjGYrKfrViqHDmS3iBPU10LoriUWO6SBgvEkCTwM94HTI/1cXgB03skDKQ212I65g8oG0BeOA8ZGDEX25SyDZ5OVOHYWmNYecBJ16WhtL5WfQOyIA5WWOZ/CCHCt9ylmkeLVl7WYyRv6NkUlmwdhN8jrAnJUDvelXjV4us1S4p5HL3s5ecNHypKnOB56ELb1qBdrEihntkOSLZ6qvWQmagQlH4yNLES50MYmvVZK0lZcAeFUkGlsJR7xc2G3U7fOSHowLOIkIbewuYceL9hycax34=
  file: xxx-Monografia-projeto.pdf
  on:
    repo: edusantana/minha-monografia
  skip_cleanup: true
#  on:
#    tags: true
dist: xenial
sudo: required
language: ruby
rvm:
- 2.3.1
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq ruby-full pdftk poppler-utils language-pack-pt
- wget https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-1-amd64.deb && sudo dpkg -i pandoc-*.deb
- wget https://github.com/abntex/limarka/raw/master/spec/dependencias/texlive-abntex2.profile
- wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz && tar -xf install-tl-unx.tar.gz && cd install-tl-* && sudo ./install-tl -no-gui -profile ../texlive-abntex2.profile -no-verify-downloads && cd ..
- export PATH=$PATH:/usr/local/texlive/2018/bin/x86_64-linux
- gem install limarka
script:
- limarka --version
- limarka exec
after_failure:
- cd /usr/local/texlive && find . -iname latexmk
- cat /usr/local/texlive/2018/install-tl.log
- cat *.log
```

Não vou criar o arquivo no repositório
